---
title: "Section 7 Explorer"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    css: custom.css
    social: menu
    df_print: paged
    navbar:
    - {title: "CCI", align: right, href: "https://defenders-cci.org"}
    - {title: "", icon: "fa-question-circle fa-lg", align: right, href: "mailto:jmalcom@defenders.org?subject=Section 7 Explorer"}
    - {title: "", icon: "fa-github fa-lg", align: right, href: "https://github.com/Defenders-CCI/"}
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DT)
library(httr)
library(lattice)
library(lubridate)
library(RCurl)
library(RJSONIO)
library(shiny)
library(shinydashboard)
library(shinyBS)
# library(shinyURL)
library(xtable)

library(leaflet)
library(maptools)
library(sp)

library(googleVis)
library(plyr)

source("data_mgmt/make_dataframes.R")
source("data_mgmt/subset_fx.R")
source("data_mgmt/summary_fx.R")
source("plot/bargraphs.R")
source("plot/histograms.R")
source("support/stick.R")
source("support/random_string.R")
source("txt/help.R")
source("txt/metadata.R")
source("txt/notes.R")
source("txt/text_styles.R")

#############################################################################
# Load the data and basic data prep
#############################################################################
# load("data/FWS_S7_clean_30Jul2015.RData")
# load("data/FWS_S7_clean_02May2016.RData")
#load("data/FWS_S7_clean_03May2016_0-4.RData")
# load("data/FWS_S7_clean_03Feb2017.RData")
load("data/FWS_S7_clean_21Mar2017.rda")

full$work_category <- as.factor(full$work_category)
full$lead_agency <- as.factor(full$lead_agency)
full$ESOffice <- as.factor(full$ESOffice)
full$region <- as.factor(full$region)
full$FY <- as.factor(full$FY)
full$consult_type <- as.factor(full$consult_type)
full$consult_complex <- as.factor(full$consult_complex)

# To facilitate adding new data, generate the vectors from the data
regions <- c("All", levels(full$region))
ESOs <- c("All", levels(full$ESOffice))
years <- as.numeric(levels(full$FY))
cons_types <- c("All", levels(full$consult_type))
cons_complx <- c("All", levels(full$consult_complex))
agencies <- c("All", levels(full$lead_agency))
work_cats <- c("All", levels(full$work_category))
formal_cons_choice <- c("All", "Yes", "No")
states <- c("All", "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA",
             "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME",
             "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM",
             "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX",
             "UT", "VA", "VT", "WA", "WI", "WV", "WY")

species <- c("All", as.character(levels(as.factor(unlist(unlist(full$spp_ev_ls))))))

# table to look up species-specific jeop/admod info
# sp_look_f <- "data/jeop_admod_spp_table_12Jun2015.tab"
sp_look_f <- "data/jeop_admod_spp_table_02May2016.tsv"
sp_ja_dat <- read.table(sp_look_f, sep="\t", header=T)

# data for ESFO-level map
eso_geo_fil <- "data/fieldOfficesTAILS.shp"
eso_geo_dat <- rgdal::readOGR(eso_geo_fil)

extent <- as.vector(bbox(eso_geo_dat))
xmin <- extent[1]
ymin <- extent[2]
xmax <- extent[3]
ymax <- extent[4]

```


Filters {.sidebar}
-----------------------------------------------------

### Filters

```{r filters, echo=FALSE}
taxa <- c("All", unique(list$taxon) %>% sort(decreasing = FALSE))
regions <- c("All", unique(list$region) %>% sort(decreasing = FALSE))

selectInput(
  "taxa1",
  "Species group",
  taxa
)

selectInput(
  "region1",
  "Region",
  regions
)
```

```{r filtering, echo=FALSE}
usr_sel <- function(df, tx, re) {
  if(tx != "All") {
    df <- filter(df, taxon == tx)
  }
  if(re != "All") {
    df <- filter(df, region == re)
  }
  #if(dim(df)[1] == 0) stop("No data matches.")
  return(df)
}

uniq_sel <- reactive({ 
  usr_sel(uniq_fiveyr, input$taxa1, input$region1) 
})

list_sel <- reactive({ 
  usr_sel(list, input$taxa1, input$region1) 
})
```

### Background

An Overview of Section 7: In 1973 the United States Congress passed, and President Nixon signed into law, the Endangered Species Act (Act) in response to the threat of extinction for many of the nation’s species. The Act remains the premier law for preventing the extinction of imperiled species: extinction has been avoided thus far for 99% of >1600 domestic listed species (CITE). Section 7 of the Act expands the role of federal agencies in conserving listed species beyond the agencies with primary responsibility (Fish and Wildlife Service [FWS] and National Marine Fisheries Service [NMFS]): "Each Federal agency shall, in consultation with [FWS and NMFS], insure that any action authorized, funded, or carried out by such agency [action agency]…is not likely to jeopardize the continued existence of any endangered species or threatened species or result in the destruction or adverse modification of habitat of such species…" The process captured in this directive is commonly referred to as “section 7 consultation. Section 7 is considered by many to be the most important section of the Act. In addition to federal agencies, many non-federal entities–including private businesses and state and local governments–actively seek a 'federal nexus' for their projects as a means of obtaining Incidental Take Permits (ITPs; see Glossary, right) for listed species. Alternative approaches to obtaining ITPs include Habitat Conservation Plans and Safe Harbor Agreements, but both of these take more time to complete than direct section 7 consultation. 


Row {data-height=750}
-----------------------------------------------------

### Distribution of most-recent five-year reviews

```{r fig1, echo=FALSE}
vline <- function(x = 0, color = "rgba(0,0,0,0.3)") {
  list(
    type = "line", 
    y0 = 0,
    y1 = 100, 
    yref = "paper",
    x0 = x, 
    x1 = x, 
    line = list(color = color,
                style = "dash")
  )
}

renderPlotly({
  cur <- uniq_sel()
  nbins <- year(uniq_fiveyr$fiveyr_date) %>% unique() %>% length() 
  if(nrow(cur) > 0) {
    plot_ly(
      data = uniq_fiveyr,
      type = "histogram",
      x = uniq_fiveyr$fiveyr_date,
      marker = list(color = "rgba(0,0,0,0.2)"),
      nbinsx = nbins * 2,
      xbins = list(start = min(uniq_fiveyr$fiveyr_date),
                   end = max(uniq_fiveyr$fiveyr_date)),
      name = "All data"
    ) %>% 
      add_histogram(x = cur$fiveyr_date,
                    marker = list( color = "#EA8439" ),
                    nbinsx = nbins * 2,
                    xbins = list(start = min(uniq_fiveyr$fiveyr_date),
                                 end = max(uniq_fiveyr$fiveyr_date)),
                    name = "Filtered") %>%
      layout(shapes = list(vline(Sys.Date() - years(5)))) %>%
      add_annotations(x = (Sys.Date() - years(4)),
                      y = 210,
                      text = "Five years past",
                      xref = "x",
                      yref = "y",
                      showarrow = FALSE,
                      font = list(color = "rgba(0,0,0,0.1)",
                                  family = 'sans-serif',
                                  size = 18)
        ) %>%
      layout(barmode = "overlay",
             xaxis = list(title = "Date of review"),
             yaxis = list(title = "Number of reviews"))
  } else {
    blank <- tibble(x = c(0), y = c(0), text = "No data match filters")
    ax <- list(
      title = "",
      zeroline = FALSE,
      showline = FALSE,
      showticklabels = FALSE,
      showgrid = FALSE
    )
    plot_ly(
      data = blank,
      type = "scatter",
      mode = "text",
      x = ~x,
      y = ~y,
      text = ~text,
      textfont = list(color = '#000000', size = 22)
    ) %>%
      layout(xaxis = ax, yaxis = ax)
  }
})
```

Row {data-height=150}
-------------------------------------------------------------
### {.value-box}

```{r info1, echo=FALSE}
flexdashboard::renderValueBox({
  flexdashboard::valueBox(
    caption = "Number of ESA-Listed Species with FWS Lead",
    value = dim(list_sel())[1],
    color = "info"
  )
})
```

### {.value-box}

```{r}
flexdashboard::renderValueBox({
  old_enough <- filter(list_sel(), listing_date < Sys.Date() - years(5))
  flexdashboard::valueBox(
    caption = "Number of Species Listed > 5 Years",
    value = dim(old_enough)[1],
    color = "info"
  )
})
```

### {.value-box}

```{r}
flexdashboard::renderValueBox({
  timely <- filter(uniq_sel(), fiveyr_date > Sys.Date() - years(5))
  flexdashboard::valueBox(
    caption = "Number of Species with Timely Reviews",
    value = dim(timely)[1],
    color = "success",
    icon = "fa-check-circle"
  )
})
```

### {.value-box}

```{r}
flexdashboard::renderValueBox({
  timely <- filter(uniq_sel(), fiveyr_date > Sys.Date() - years(5))
  old_enough <- filter(list_sel(), listing_date < Sys.Date() - years(5))
  flexdashboard::valueBox(
    caption = "Number of Species with Outdated Reviews",
    value = dim(old_enough)[1] - dim(timely)[1],
    color = "danger",
    icon = "fa-times-circle"
  )
})
```

